version: "3.7"

services:
  db:
    container_name: db
    image: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - utils/.env

  app:
    depends_on:
      - db
    container_name: app
    build:
      context: ./app/.

    env_file:
      - app/utils/.env
    environment:
      - DB_HOST=db
    volumes:
      - ./app:/app/app_volume
    ports:
      - 8003:8061