version: "3.9"

services:
  db:
    container_name: db
    image: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - utils/.env

  app:
    depends_on:
      - db
    container_name: app
    build:
      context: ./app/.

    env_file:
      - app/utils/.env
    environment:
      - DB_HOST=db
    volumes:
      - ./app:/app/app_volume
    ports:
      - 8003:8061

  link_maker_redis:
    container_name: link_maker_redis
    image: redis:latest
#    environment:
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
#      - REDIS_USER=${REDIS_USER}
#      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6380:6379"
    env_file:
      - utils/.env