version: "3.9"

services:
  db:
    container_name: db
    image: postgres
    expose:
      - 5435
    ports:
      - 5435:5435
    env_file:
      - app/utils/.env
    environment:
      - POSTGRES_DB=flashcards
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345

  test_db:
    container_name: test_db
    image: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - app/utils/.env
    environment:
      - POSTGRES_DB=flashcards_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
  app:
    depends_on:
      - test_db
      - link_maker_redis
    container_name: app
    build:
      context: ./app/.
    env_file:
      - app/utils/.env
    environment:
      - DB_HOST=test_db
      - DB_TEST_HOST=test_db
      - REDIS_HOST=link_maker_redis
      - APP_HOST=0.0.0.0
      - REDIS_PORT=6379
    volumes:
      - ./app:/app/app_volume
    ports:
      - 8003:8061
#    command: ["/app/app_runned.sh"]


  link_maker_redis:
    container_name: link_maker_redis
    image: redis:latest
#    environment:
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
#      - REDIS_USER=${REDIS_USER}
#      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    expose:
      - 6380
    ports:
      - "6383:6379"
    env_file:
      - app/utils/.env